### ISSUE TITLE
Remove my name from current maintainers list

### ISSUE THREAD

**Issue by twhiston** [ibrows/elastic_search#11]
Hi Alessio,
Can you alter the readme to remove me as a current contributor as I dont have repo access any more and I'm not coming back to Drupal. If you wish to list me as a past contributor that would be nice, but up to you.

**Comment by aless-io** [comment]
Hello Tom,
Sure, I proceeded to change those details and moved your name in the past contributors.
Thanks.

**Comment by twhiston** [comment]
Thanks mate 👍
